# Generated by Django 4.2.16 on 2024-12-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='location',
            field=models.CharField(default='co. Cork, Cork', max_length=100),
        ),
    ]
