# Generated by Django 4.2.16 on 2024-12-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ad_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='location',
            field=models.CharField(default='Ireland, co. Cork, Cork', max_length=100),
        ),
    ]
