# Generated by Django 4.2.16 on 2024-12-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ad_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
