# Generated by Django 4.2.16 on 2024-12-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_ad_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='is_new',
        ),
        migrations.AddField(
            model_name='ad',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used')], default='new', max_length=4),
        ),
    ]
