# Generated by Django 4.2.16 on 2024-12-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_remove_ad_is_new_ad_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
